trigger:
- master

pool:
  name: 'Default'
  demands:
    - agent.name -equals RAKESH

steps:
# Run Maven build using locally installed JDK and Maven
- task: Maven@3
  inputs:
    mavenPomFile: 'pom.xml'
    mavenOptions: '-Xmx3072m'
    javaHomeOption: 'UserInput'
    jdkUserInputPath: 'C:\\Program Files\\Java\\jdk-17'
    mavenDirectory: 'C:\\Users\\ra301\\Downloads\\apache-maven-3.9.9-bin (1)\\apache-maven-3.9.9'
    publishJUnitResults: true
    testResultsFiles: '**/surefire-reports/TEST-*.xml'
    goals: 'package'

# Run the generated JAR file
- script: |
    java -jar target/Hello2-0.0.1-SNAPSHOT.jar
  displayName: 'Run Compiled Java Application'
