trigger:
- master

pool:
  name: 'Default'
  demands:
    - agent.name -equals RAKESH

steps:
# Run Maven build using locally installed JDK and Maven
- task: Maven@3
  inputs:
    mavenPomFile: 'pom.xml'
    mavenOptions: '-Xmx3072m'
    javaHomeOption: 'UserInput'
    jdkUserInputPath: 'C:\\Program Files\\Java\\jdk-17'
    mavenDirectory: 'C:\\Users\\ra301\\Downloads\\apache-maven-3.9.9-bin (1)\\apache-maven-3.9.9'
    publishJUnitResults: true
    testResultsFiles: '**/surefire-reports/TEST-*.xml'
    goals: 'package'

# Run the generated JAR file
- script: |
    java -jar target/Hello2-0.0.1-SNAPSHOT.jar
  displayName: 'Run Compiled Java Application'

  https://dev.azure.com/ra3013646/Project%201/_build/results?buildId=41&view=logs&j=12f1170f-54f2-53f3-20dd-22fc7dff55f9&t=9c939e41-62c2-5605-5e05-fc3554afc9f5
4fa9GAjDhFVKFID5Wf6YHDapMMFzbNVETHVvoR1iKBND1cQOFOYkJQQJ99BFACAAAAAAAAAAAAASAZDO4OOy
Pipeline stage view plugin 
Maven integration plugin 
Gradle integration plugin 
Github integration plugin
