trigger:
- master

pool:
  name: 'Default'
  demands:
    - agent.name -equals RAKESH

steps:
# Set JAVA_HOME environment variable to your JDK 17 path
- powershell: |
    echo "##vso[task.setvariable variable=JAVA_HOME]C:\Program Files\Java\jdk-17"
  displayName: 'Set JAVA_HOME to JDK 17'

# Run Maven build using JDK 17
- task: Maven@3
  inputs:
    mavenPomFile: 'pom.xml'
    mavenOptions: '-Xmx3072m'
    javaHomeOption: 'Environment'
    publishJUnitResults: true
    testResultsFiles: '**/surefire-reports/TEST-*.xml'
    goals: 'package'
